---
title: "Correlation DEGs"
author: "Kimberly Olney, PhD"
date: "October 20th 2025"
output:
  pdf_document: default
params:
  project: sepsis
---

# Set up working enivornment
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = ".")
getwd()
```

```{r libraries, message=FALSE, warning=FALSE}
source("/tgen_labs/jfryer/kolney/sepsis_human/scripts/file_paths_and_colours_pigs.R")
rm(kidney_metadata, metadata_extra)
metadata_pigs <- metadata
source("/tgen_labs/jfryer/kolney/sepsis_human/scripts/file_paths_and_colours_human.R")
tissue <- "Kidney"
metadata <- subset(metadata, tissue == "Kidney")
metadata_human <- metadata
rm(metadata)
projectID <- "human_and_pig"
library(readxl)
```

# Figure 1 Human
### a) bulk volcano
```{r bulk_volcano}
# a) bulk volcano
allComparisons <- c("sepsis_vs_control")
for (i in allComparisons) {
  group1_vs_group2 <-
    read.delim(paste0("../../results/human_kidney_both_sexes/DEGs/", i,"_q1.00_Kidney.txt"))
    i <- gsub("_", " ", i)
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > .25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }
  group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
  data <- group1_vs_group2
  num <- subset(data, (adj.P.Val < 0.05 & logFC < -.25)  | (adj.P.Val < 0.05 & logFC > .25 ))
  # Identify up- and down-regulated genes
  up_num <- sum(data$logFC > .25 & data$adj.P.Val < 0.05)
  down_num <- sum(data$logFC < -.25 & data$adj.P.Val < 0.05)
  num <- nrow(num)
  if (num != 0) {
    up <- data[data$color_adjpval_0.05 == 1,]
    up10 <- up[1:10,]
    upFold <- subset(up, logFC > 1)
    upFold <- upFold[!(upFold$gene_name %in% up10$gene_name),]
    down <- data[data$color_adjpval_0.05 == 2,]
    down10 <- down[1:10,]
    downFold <- subset(down, logFC < -1)
    downFold <- downFold[!(downFold$gene_name %in% down10$gene_name),]
    if (!1 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("blue", "gray")
    } else if (!2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("red", "gray")
    } else if (!1 %in% unique(data$color_adjpval_0.05) &&
               !2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("gray")
    } else {
      my_colors <- c("red", "blue", "gray")
    }
    hadjpval <- (-log10(max(data$P.Value[data$adj.P.Val < 0.05],
                            na.rm = TRUE)))
    negFC <- c(-.25)
    posFC <- c(.25) 
    bulk_vol_plot <-
      ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = .7) +
      theme_bw() +
      theme(legend.position = "none") +
      scale_color_manual(values = my_colors) +
      labs(
        title = "",
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      geom_hline(yintercept = hadjpval,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0("human ",  i, "\nq < 0.05 & |log2FC| > 0.25")) +
      # geom_text_repel(
      #   data = up10,
      #   aes(
      #     x = logFC,
      #     y = -log10(P.Value),
      #     label = gene_name
      #   ),
      #   color = "maroon",
      #   fontface = "italic",
      #   size = 1.8,
      #   max.overlaps = getOption("ggrepel.max.overlaps", default = 5)
      # ) +
      # geom_text_repel(
      #   data = upFold,
      #   aes(
      #     x = logFC,
      #     y = -log10(P.Value),
      #     label = gene_name
      #   ),
      #   color = "maroon",
      #   fontface = "italic",
      #   size = 1.8,
      #   max.overlaps = getOption("ggrepel.max.overlaps", default = 5)
      # ) +
      # geom_text_repel(
      #   data = down10,
      #   aes(
      #     x = logFC,
      #     y = -log10(P.Value),
      #     label = gene_name
      #   ),
      #   color = "navyblue",
      #   fontface = "italic",
      #   size = 1.8,
      #   max.overlaps = getOption("ggrepel.max.overlaps", default = 3)
      # ) +
      # geom_text_repel(
      #   data = downFold,
      #   aes(
      #     x = logFC,
      #     y = -log10(P.Value),
      #     label = gene_name
      #   ),
      #   color = "navyblue",
      #   fontface = "italic",
      #   size = 1.8,
      #   max.overlaps = getOption("ggrepel.max.overlaps", default = 5)
      # ) +
  theme(
    axis.title.x = element_text(size = 8),
    axis.text.x = element_text(size = 8),
    axis.title.y = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    legend.title = element_text(size = 8), 
    legend.text = element_text(size = 8),  
    plot.title = element_text(size = 8)    
  ) +
  scale_x_continuous(limits = c(-4, 4.5), breaks = seq(-4, 4.5, 2)) +
  scale_y_continuous(limits = c(0, 8.35), breaks = seq(0, 8, 2)) +
  annotate("text",
           x = 3.95, # Adjust x position as needed
           y = 8.35,    # Adjust y position as needed
           label = paste("Up =", up_num),
           color = "maroon",
           size = 2.5,
            fontface = "bold",
           hjust = 1, vjust = 1) +
  annotate("text",
           x = -3.95, # Adjust x position as needed
           y = 8.35,    # Adjust y position as needed
           label = paste("Down =", down_num),
           color = "navyblue",
           fontface = "bold",
           size = 2.5,
           hjust = 0, vjust = 1)
bulk_vol_plot 
    
  }
  } 
```

### b) metascape
```{r bulk_metascape}
# Metascape Enrichment 
#read in enrichment analysis results
up_enrich_results <-
  read_excel(
    paste0(
      "../../results/human_kidney_both_sexes/metascape/sepsis_vs_control_upregulated/metascape_result.xlsx"
    ), sheet = 2
  )

down_enrich_results <-
  read_excel(
    paste0(
      "../../results/human_kidney_both_sexes/metascape/sepsis_vs_control_downregulated/metascape_result.xlsx"
    ), sheet = 2
  )

# select the GO term IDs we want to show in the plot
GO_ID_up <-
  c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
  )
GO_ID_down <- c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
   # "18_Summary",
 #   "19_Summary", 
    "20_Summary"
)

up_enrich_results_subset <-
  up_enrich_results[up_enrich_results$GroupID %in% GO_ID_up, ]
up_enrich_results_subset$Cluster <- c("upregulated")
up_enrich_results_subset$Description <-
  factor(up_enrich_results_subset$Description,
         levels = up_enrich_results_subset$Description)
up_enrich_results_subset$Description <-
  fct_rev(up_enrich_results_subset$Description)

down_enrich_results_subset <-
  down_enrich_results[down_enrich_results$GroupID %in% GO_ID_down, ]
down_enrich_results_subset$Cluster <- c("downregulated")
down_enrich_results_subset$Description <-
  factor(down_enrich_results_subset$Description,
         levels = down_enrich_results_subset$Description)
down_enrich_results_subset$Description <-
  fct_rev(down_enrich_results_subset$Description)

# get the number of genes in each summary
up_gene_count <-
  strsplit(as.character(up_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
up_gene_count_df <-
  data.frame(matrix(
    unlist(up_gene_count),
    nrow = length(up_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
up_enrich_results_subset$InTerm <- as.numeric(up_gene_count_df$X1)
up_enrich_results_subset$InList <- as.numeric(up_gene_count_df$X2)

down_gene_count <-
  strsplit(as.character(down_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
down_gene_count_df <-
  data.frame(matrix(
    unlist(down_gene_count),
    nrow = length(down_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
down_enrich_results_subset$InTerm <- as.numeric(down_gene_count_df$X1)
down_enrich_results_subset$InList <- as.numeric(down_gene_count_df$X2)

# combine together
up_and_down_enrich_results_subset <- rbind(up_enrich_results_subset, down_enrich_results_subset)

 up_and_down_enrich_results_subset$Description <-
       gsub(
         "Diseases of signal transduction by growth factor receptors and second messengers",
         "Diseases of signal transduction",
         up_and_down_enrich_results_subset$Description
       )
  up_and_down_enrich_results_subset$Description <-
       gsub(
         "Signaling by Rho GTPases, Miro GTPases and RHOBTB3",
         "Signaling by Rho GTPases",
         up_and_down_enrich_results_subset$Description
       )
 
up_and_down_enrich_results_subset$Description <-
       gsub(
         "positive regulation of cellular component biogenesis",
         "pos reg cellular component biogenesis",
         up_and_down_enrich_results_subset$Description
       )
 
 up_and_down_enrich_results_subset$Description <-
       gsub(
         "negative regulation of cellular component organization",
         "neg reg cellular component organization",
         up_and_down_enrich_results_subset$Description
       )
 
  up_and_down_enrich_results_subset$Description <-
       gsub(
         "proteolysis involved in protein catabolic process",
         "proteolysis in protein catabolic process",
         up_and_down_enrich_results_subset$Description
       )
 
  up_and_down_enrich_results_subset$Description <-
       gsub(
         "carbohydrate derivative biosynthetic process",
         "carbohydrate biosynthetic process",
         up_and_down_enrich_results_subset$Description
       )
  
  up_and_down_enrich_results_subset$Description <-
       gsub(
         "regulation of response to biotic stimulus",
         "reg of response to biotic stimulus",
         up_and_down_enrich_results_subset$Description
       )

up_and_down_enrich_results_subset$Description <-
       gsub(
         "regulation of cell projection organization",
         "reg of cell projection organization",
         up_and_down_enrich_results_subset$Description
       ) 
up_and_down_enrich_results_subset$Description <-
       gsub(
         "regulation of cellular response to stress",
         "reg of cellular response to stress",
         up_and_down_enrich_results_subset$Description
       ) 
up_and_down_enrich_results_subset$Description <-
  factor(up_and_down_enrich_results_subset$Description, levels = unique(up_and_down_enrich_results_subset$Description)) 

up_and_down_enrich_results_subset$Description <- fct_rev(up_and_down_enrich_results_subset$Description)

remove(
  down_enrich_results,
  down_gene_count,
  down_gene_count_df,
  up_enrich_results,
  up_gene_count,
  up_gene_count_df
)

up_and_down_enrich_plot <-
  ggplot(data = up_and_down_enrich_results_subset, aes(x = InTerm, y = Description)) +
  ggplot2::facet_grid(~ Cluster, scales = "free") +
  geom_bar(stat = "identity", aes(fill = LogP), width = .7, position = position_dodge(width = .2)) +
  theme_bw() +
 # ggtitle(paste0(tissue," enrichment summaries")) +
  labs(x = "Gene count", y = NULL) +
  guides(fill = guide_legend(title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)"))) +
  scale_fill_gradientn(
    colours = c(colors=natparks.pals("Denali")),
    guide = "legend",
    limits = c(-25,-1)
  ) +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.1, 0.2, 0, 0.2, "cm"), 
          plot.title = element_text(size = 8, hjust = -3.25, vjust=0, margin = margin(0,0,0,0)))
up_and_down_enrich_plot

addSmallLegend <- function(myPlot, pointSize = 3, textSize = 6, spaceLegend = .5) {
    myPlot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}

# Apply on original plot
up_and_down_enrich_plot <- addSmallLegend(up_and_down_enrich_plot)
```


### Figure 1 combined
```{r figure1_combined}
# Option 2
figure1 <-
  ggarrange(
    bulk_vol_plot,
    up_and_down_enrich_plot,
    ncol = 2,
  widths = c(2, 4.75), 
  labels = c("A","B"), 
  font.label = list(size = 10)
    )
figure1
path <- paste0("../../manuscript_figures/Figure_1_human")
saveToPDF(paste0(path, ".pdf"), width = 7, height = 4.5)
```

# Figure 2 Pig
### a) bulk volcano
```{r bulk_volcano}
# a) bulk volcano
allComparisons <- c("Ecoli_vs_Saline")
for (i in allComparisons) {
  group1_vs_group2 <-
    read.delim(paste0("../../results/pigs_kidney/DEGs/", i,"_q1.00_Kidney.txt"))
    i <- gsub("_", " ", i)
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > .25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }
  group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
  data <- group1_vs_group2
  num <- subset(data, (adj.P.Val < 0.05 & logFC < -.25)  | (adj.P.Val < 0.05 & logFC > .25 ))
  # Identify up- and down-regulated genes
  up_num <- sum(data$logFC > .25 & data$adj.P.Val < 0.05)
  down_num <- sum(data$logFC < -.25 & data$adj.P.Val < 0.05)
  num <- nrow(num)
  if (num != 0) {
    up <- data[data$color_adjpval_0.05 == 1,]
    up10 <- up[1:10,]
    upFold <- subset(up, logFC > 1)
    upFold <- upFold[!(upFold$gene_name %in% up10$gene_name),]
    down <- data[data$color_adjpval_0.05 == 2,]
    down10 <- down[1:10,]
    downFold <- subset(down, logFC < -1)
    downFold <- downFold[!(downFold$gene_name %in% down10$gene_name),]
    if (!1 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("blue", "gray")
    } else if (!2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("red", "gray")
    } else if (!1 %in% unique(data$color_adjpval_0.05) &&
               !2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("gray")
    } else {
      my_colors <- c("red", "blue", "gray")
    }
    hadjpval <- (-log10(max(data$P.Value[data$adj.P.Val < 0.05],
                            na.rm = TRUE)))
    negFC <- c(-.25)
    posFC <- c(.25) 
    bulk_vol_plot <-
      ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = .7) +
      theme_bw() +
      theme(legend.position = "none") +
      scale_color_manual(values = my_colors) +
      labs(
        title = "",
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      geom_hline(yintercept = hadjpval,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0("pig E.coli vs saline \nq < 0.05 & |log2FC| > 0.25")) +
      # geom_text_repel(
      #   data = up10,
      #   aes(
      #     x = logFC,
      #     y = -log10(P.Value),
      #     label = gene_name
      #   ),
      #   color = "maroon",
      #   fontface = "italic",
      #   size = 1.8,
      #   max.overlaps = getOption("ggrepel.max.overlaps", default = 5)
      # ) +
      # geom_text_repel(
      #   data = upFold,
      #   aes(
      #     x = logFC,
      #     y = -log10(P.Value),
      #     label = gene_name
      #   ),
      #   color = "maroon",
      #   fontface = "italic",
      #   size = 1.8,
      #   max.overlaps = getOption("ggrepel.max.overlaps", default = 5)
      # ) +
      # geom_text_repel(
      #   data = down10,
      #   aes(
      #     x = logFC,
      #     y = -log10(P.Value),
      #     label = gene_name
      #   ),
      #   color = "navyblue",
      #   fontface = "italic",
      #   size = 1.8,
      #   max.overlaps = getOption("ggrepel.max.overlaps", default = 3)
      # ) +
      # geom_text_repel(
      #   data = downFold,
      #   aes(
      #     x = logFC,
      #     y = -log10(P.Value),
      #     label = gene_name
      #   ),
      #   color = "navyblue",
      #   fontface = "italic",
      #   size = 1.8,
      #   max.overlaps = getOption("ggrepel.max.overlaps", default = 5)
      # ) +
  theme(
    axis.title.x = element_text(size = 8),
    axis.text.x = element_text(size = 8),
    axis.title.y = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    legend.title = element_text(size = 8), 
    legend.text = element_text(size = 8),  
    plot.title = element_text(size = 8)    
  ) +
  scale_x_continuous(limits = c(-7, 8.5), breaks = seq(-7, 8.5, 2)) +
  scale_y_continuous(limits = c(0, 10.35), breaks = seq(0, 10, 2)) +
  annotate("text",
           x = 7, # Adjust x position as needed
           y = 10.35,    # Adjust y position as needed
           label = paste("Up =", up_num),
           color = "maroon",
           size = 2.5,
            fontface = "bold",
           hjust = 1, vjust = 1) +
  annotate("text",
           x = -7, # Adjust x position as needed
           y = 10.35,    # Adjust y position as needed
           label = paste("Down =", down_num),
           color = "navyblue",
           fontface = "bold",
           size = 2.5,
           hjust = 0, vjust = 1)
bulk_vol_plot 
    
  }
  } 
```

### b) metascape
```{r bulk_metascape}
# Metascape Enrichment 
#read in enrichment analysis results
up_enrich_results <-
  read_excel(
    paste0(
      "../../results/pigs_kidney/metascape/Ecoli_saline_upregulated/metascape_result.xlsx"
    ), sheet = 2
  )

down_enrich_results <-
  read_excel(
    paste0(
      "../../results/pigs_kidney/metascape/Ecoli_saline_downregulated/metascape_result.xlsx"
    ), sheet = 2
  )

# select the GO term IDs we want to show in the plot
GO_ID_up <-
  c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
  )
GO_ID_down <- c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
)

up_enrich_results_subset <-
  up_enrich_results[up_enrich_results$GroupID %in% GO_ID_up, ]
up_enrich_results_subset$Cluster <- c("upregulated")
up_enrich_results_subset$Description <-
  factor(up_enrich_results_subset$Description,
         levels = up_enrich_results_subset$Description)
up_enrich_results_subset$Description <-
  fct_rev(up_enrich_results_subset$Description)

down_enrich_results_subset <-
  down_enrich_results[down_enrich_results$GroupID %in% GO_ID_down, ]
down_enrich_results_subset$Cluster <- c("downregulated")
down_enrich_results_subset$Description <-
  factor(down_enrich_results_subset$Description,
         levels = down_enrich_results_subset$Description)
down_enrich_results_subset$Description <-
  fct_rev(down_enrich_results_subset$Description)

# get the number of genes in each summary
up_gene_count <-
  strsplit(as.character(up_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
up_gene_count_df <-
  data.frame(matrix(
    unlist(up_gene_count),
    nrow = length(up_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
up_enrich_results_subset$InTerm <- as.numeric(up_gene_count_df$X1)
up_enrich_results_subset$InList <- as.numeric(up_gene_count_df$X2)

down_gene_count <-
  strsplit(as.character(down_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
down_gene_count_df <-
  data.frame(matrix(
    unlist(down_gene_count),
    nrow = length(down_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
down_enrich_results_subset$InTerm <- as.numeric(down_gene_count_df$X1)
down_enrich_results_subset$InList <- as.numeric(down_gene_count_df$X2)

# combine together
up_and_down_enrich_results_subset <- rbind(up_enrich_results_subset, down_enrich_results_subset)

 up_and_down_enrich_results_subset$Description <-
       gsub(
         up_and_down_enrich_results_subset$Description[19],
         "reg of canonical NF−kappaB signal transduction",
         up_and_down_enrich_results_subset$Description
       )

 up_and_down_enrich_results_subset$Description
  up_and_down_enrich_results_subset$Description <-
       gsub(
         "positive regulation of response to external stimulus",
         "pos reg of response to external stimulus",
         up_and_down_enrich_results_subset$Description
       )
 
 
up_and_down_enrich_results_subset$Description <-
  factor(up_and_down_enrich_results_subset$Description, levels = unique(up_and_down_enrich_results_subset$Description)) 

up_and_down_enrich_results_subset$Description <- fct_rev(up_and_down_enrich_results_subset$Description)

remove(
  down_enrich_results,
  down_gene_count,
  down_gene_count_df,
  up_enrich_results,
  up_gene_count,
  up_gene_count_df
)

up_and_down_enrich_plot <-
  ggplot(data = up_and_down_enrich_results_subset, aes(x = InTerm, y = Description)) +
  ggplot2::facet_grid(~ Cluster, scales = "free") +
  geom_bar(stat = "identity", aes(fill = LogP), width = .7, position = position_dodge(width = .2)) +
  theme_bw() +
 # ggtitle(paste0(tissue," enrichment summaries")) +
  labs(x = "Gene count", y = NULL) +
  guides(fill = guide_legend(title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)"))) +
  scale_fill_gradientn(
    colours = c(colors=natparks.pals("Denali")),
    guide = "legend",
    limits = c(-101,-1)
  ) +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.1, 0.2, 0, 0.2, "cm"), 
          plot.title = element_text(size = 8, hjust = -3.25, vjust=0, margin = margin(0,0,0,0)))
up_and_down_enrich_plot

addSmallLegend <- function(myPlot, pointSize = 3, textSize = 6, spaceLegend = .5) {
    myPlot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}

# Apply on original plot
up_and_down_enrich_plot <- addSmallLegend(up_and_down_enrich_plot)
```


### Figure 2 combined
```{r figure1_combined}
# Option 2
figure2 <-
  ggarrange(
    bulk_vol_plot,
    up_and_down_enrich_plot,
    ncol = 2,
  widths = c(2, 4.75), 
  labels = c("A","B"), 
  font.label = list(size = 10)
    )
figure2
path <- paste0("../../manuscript_figures/Figure_2_pig")
saveToPDF(paste0(path, ".pdf"), width = 7, height = 4.5)
```